import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { customers as seedCustomers, inventory as seedInventory, jobs as seedJobs, movements } from './data/mockData'
import type { Contact, InventoryItem, ModuleKey, PrintJob, PrintJobStatus } from './domain/models'

type ModalKind = 'job' | 'quote' | 'contact' | 'item' | 'movement' | 'jobDetail' | null
const money = new Intl.NumberFormat('en-MY', { style: 'currency', currency: 'MYR' })
const date = new Intl.DateTimeFormat('en-MY', { day: '2-digit', month: '2-digit', year: 'numeric' })
const nav: { key: ModuleKey; label: string; icon: string }[] = [
  { key: 'dashboard', label: 'Dashboard', icon: '▦' }, { key: 'jobs', label: 'Print Jobs', icon: '▣' },
  { key: 'documents', label: 'Documents', icon: '▤' }, { key: 'contacts', label: 'Contacts', icon: '♙' },
  { key: 'inventory', label: 'Items & BOM', icon: '◇' }, { key: 'stock', label: 'Stock Ledger', icon: '⇄' },
  { key: 'finance', label: 'Finance', icon: '◒' }, { key: 'insights', label: 'Insights', icon: '⌁' },
]

export default function PrototypeApp() {
  const [authenticated, setAuthenticated] = useState(false)
  const [active, setActive] = useState<ModuleKey>('dashboard')
  const [modal, setModal] = useState<ModalKind>(null)
  const [selectedJob, setSelectedJob] = useState<PrintJob | null>(null)
  const [jobs, setJobs] = useState(seedJobs)
  const [contacts, setContacts] = useState(seedCustomers)
  const [items, setItems] = useState(seedInventory)
  const [toast, setToast] = useState('')

  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(''), 2600) }
  function open(kind: ModalKind, job?: PrintJob) { setSelectedJob(job ?? null); setModal(kind) }
  if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />

  const pages: Record<ModuleKey, ReactNode> = {
    dashboard: <Dashboard jobs={jobs} items={items} go={setActive} open={open} />,
    jobs: <Jobs jobs={jobs} open={open} />,
    documents: <Documents open={open} />,
    contacts: <Contacts contacts={contacts} open={open} />,
    inventory: <Inventory items={items} open={open} />,
    stock: <Stock open={open} />,
    finance: <Finance />,
    insights: <Insights />,
    settings: <Settings notify={notify} />,
  }

  return <div className="app-shell">
    <aside className="sidebar"><Brand /><nav>{nav.map((item) => <button key={item.key} className={active === item.key ? 'active' : ''} onClick={() => setActive(item.key)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-foot"><div className="plan"><small>Prototype workspace</small><b>MVP presentation</b></div><button className={active === 'settings' ? 'active' : ''} onClick={() => setActive('settings')}>⚙ Settings</button></div></aside>
    <header className="mobile-header"><Brand compact /><button aria-label="Notifications">○</button></header>
    <main><header className="topbar"><div><span className="workspace-dot" /> Three Line Apparel</div><div className="top-actions"><span className="demo-chip">Interactive prototype</span><button aria-label="Search">⌕</button><button aria-label="Notifications">○</button><div className="user"><span>AM</span><div><b>Amir</b><small>Owner</small></div></div></div></header><div className="content">{pages[active]}</div></main>
    <nav className="bottom-nav">{nav.slice(0, 5).map((item) => <button key={item.key} className={active === item.key ? 'active' : ''} onClick={() => setActive(item.key)}><span>{item.icon}</span><small>{item.label}</small></button>)}<button onClick={() => setActive('settings')}><span>•••</span><small>More</small></button></nav>
    {modal && <Modal kind={modal} job={selectedJob} close={() => setModal(null)} onJob={(job) => { setJobs([job, ...jobs]); notify(`${job.id} created successfully`) }} onContact={(contact) => { setContacts([contact, ...contacts]); notify(`${contact.name} added`) }} onItem={(item) => { setItems([item, ...items]); notify(`${item.name} added`) }} notify={notify} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </div>
}

function Login({ onLogin }: { onLogin: () => void }) {
  const [show, setShow] = useState(false)
  function submit(event: FormEvent) { event.preventDefault(); onLogin() }
  return <div className="login-page"><section className="login-story"><Brand /><div><p className="eyebrow">Made for Malaysian print teams</p><h1>Every order.<br />One clear flow.</h1><p>From quotation and artwork approval to production, stock, invoicing, and delivery.</p></div><div className="login-stats"><span><b>8</b> connected modules</span><span><b>MYR</b> local-first finance</span><span><b>Mobile</b> factory ready</span></div></section><section className="login-card"><div className="login-form"><span className="prototype-label">Clickable MVP</span><h2>Welcome back</h2><p>Use the demo details below to explore the prototype.</p><form onSubmit={submit}><label>Email<input type="email" defaultValue="owner@mzprintflow.demo" required /></label><label>Password<div className="password"><input type={show ? 'text' : 'password'} defaultValue="prototype" required /><button type="button" onClick={() => setShow(!show)}>{show ? 'Hide' : 'Show'}</button></div></label><div className="form-between"><label className="check"><input type="checkbox" defaultChecked /> Remember me</label><button type="button" className="link-button">Forgot password?</button></div><button className="primary login-button">Enter demo workspace →</button></form><small>No real account or backend is used in this prototype.</small></div></section></div>
}

function Dashboard({ jobs, items, go, open }: { jobs: PrintJob[]; items: InventoryItem[]; go: (key: ModuleKey) => void; open: (kind: ModalKind, job?: PrintJob) => void }) {
  const low = items.filter((item) => item.quantity <= item.reorderLevel).length
  return <><Heading eyebrow="Thursday, 27 August" title="Production overview" text="Here is what needs attention across your shop." action="+ New print job" onAction={() => open('job')} /><section className="metrics"><Metric label="Active jobs" value={jobs.filter((x) => x.status !== 'Completed').length} note="Across production" /><Metric label="Due this week" value="2" note="All currently on track" /><Metric label="Low-stock items" value={low} note="Require review" danger /><Metric label="Completed" value={jobs.filter((x) => x.status === 'Completed').length} note="This month" /></section><section className="dashboard-grid"><article className="panel"><PanelTitle eyebrow="Live production" title="Today’s floor" action="View all" onAction={() => go('jobs')} /><div className="stage-grid">{['Queued', 'Printing', 'Finishing', 'Quality check'].map((stage, i) => <div key={stage}><span>{stage}</span><strong>{[2, 1, 1, 0][i]}</strong><div className="bar"><i style={{ width: `${[70, 45, 35, 8][i]}%` }} /></div></div>)}</div><div className="job-stack">{jobs.slice(0, 3).map((job) => <button className="job-row clickable" onClick={() => open('jobDetail', job)} key={job.id}><div className="job-id">{job.id.slice(-2)}</div><div><strong>{job.title}</strong><small>{job.customerName} · {job.quantity} units</small></div><Status value={job.status} /><time>{date.format(new Date(job.dueDate))}</time></button>)}</div></article><aside className="panel attention-panel"><div className="panel-title"><div><p className="eyebrow">Action centre</p><h2>Needs attention</h2></div><span className="count">3</span></div><Notice tone="warning" title="Proof waiting for approval" text="J-1048 · 2 days waiting" /><Notice tone="danger-bg" title="Black DTF ink is low" text="1.2 L remaining · threshold 2 L" /><Notice tone="info" title="Invoice balance due" text={`INV-2041 · ${money.format(840)}`} /></aside></section></>
}

function Jobs({ jobs, open }: { jobs: PrintJob[]; open: (kind: ModalKind, job?: PrintJob) => void }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'All' | PrintJobStatus>('All')
  const shown = useMemo(() => jobs.filter((job) => (filter === 'All' || job.status === filter) && `${job.id} ${job.title} ${job.customerName}`.toLowerCase().includes(query.toLowerCase())), [jobs, query, filter])
  return <><Heading eyebrow="Production" title="Print jobs" text="Plan, track, and complete every customer order." action="+ New job" onAction={() => open('job')} /><section className="panel"><div className="toolbar"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search job, customer, or title" /><select value={filter} onChange={(e) => setFilter(e.target.value as typeof filter)}>{['All', 'Pending', 'In Production', 'Quality Check', 'Completed', 'Cancelled'].map((x) => <option key={x}>{x}</option>)}</select><button className="secondary">Calendar</button></div><div className="table-wrap"><table><thead><tr><th>Job</th><th>Customer</th><th>Method</th><th>Qty</th><th>Due</th><th>Status</th><th /></tr></thead><tbody>{shown.map((job) => <tr key={job.id} onClick={() => open('jobDetail', job)} className="clickable-row"><td><b>{job.id}</b><small>{job.title}</small></td><td>{job.customerName}</td><td>{job.method}</td><td>{job.quantity}</td><td>{date.format(new Date(job.dueDate))}</td><td><Status value={job.status} /></td><td>→</td></tr>)}</tbody></table></div></section></>
}

function Documents({ open }: { open: (kind: ModalKind) => void }) { return <><Heading eyebrow="Sales" title="Documents" text="Create quotations, invoices, and payment records." action="+ New quotation" onAction={() => open('quote')} /><section className="panel"><div className="segmented"><button className="active">Invoices</button><button>Quotations</button></div><table><thead><tr><th>Document</th><th>Customer</th><th>Date</th><th>Amount</th><th>Status</th></tr></thead><tbody><tr><td><b>INV-2041</b><small>J-1047</small></td><td>Northstar FC</td><td>27/08/2026</td><td>{money.format(1240)}</td><td><span className="status status-pending">Partially paid</span></td></tr><tr><td><b>INV-2040</b><small>J-1045</small></td><td>Bina Community</td><td>25/08/2026</td><td>{money.format(2700)}</td><td><span className="status status-completed">Paid</span></td></tr></tbody></table></section></> }
function Contacts({ contacts, open }: { contacts: Contact[]; open: (kind: ModalKind) => void }) { return <><Heading eyebrow="CRM" title="Contacts" text="Keep customers and suppliers in one organised directory." action="+ Add contact" onAction={() => open('contact')} /><section className="cards">{contacts.map((person) => <article className="contact-card" key={person.id}><div className="avatar">{person.name.split(' ').map((x) => x[0]).slice(0, 2)}</div><div><h3>{person.name}</h3><p>{person.type} · {person.phone}</p><small>{person.email}</small></div><button className="icon-button">•••</button></article>)}</section></> }
function Inventory({ items, open }: { items: InventoryItem[]; open: (kind: ModalKind) => void }) { return <><Heading eyebrow="Inventory master" title="Items & BOM" text="Manage raw materials, finished goods, and production recipes." action="+ Add item" onAction={() => open('item')} /><section className="cards">{items.map((item) => <article className="inventory-card" key={item.id}><div className="item-top"><span className="item-icon">{item.category === 'Garment' ? 'T' : '◈'}</span><span className={item.quantity <= item.reorderLevel ? 'stock-low' : 'stock-ok'}>{item.quantity <= item.reorderLevel ? 'Low stock' : 'Healthy'}</span></div><h3>{item.name}</h3><p>{item.category} · {item.sku}</p><div className="quantity"><strong>{item.quantity}</strong><span>{item.unit} available</span></div><small>Reorder at {item.reorderLevel} {item.unit}</small></article>)}</section></> }
function Stock({ open }: { open: (kind: ModalKind) => void }) { return <><Heading eyebrow="Inventory movements" title="Stock ledger" text="An auditable history of every receipt, consumption, and adjustment." action="+ Log movement" onAction={() => open('movement')} /><section className="panel table-wrap"><table><thead><tr><th>Date</th><th>Item</th><th>Movement</th><th>Quantity</th><th>Reference</th><th>Balance</th></tr></thead><tbody>{movements.map((move) => <tr key={move.id}><td>{date.format(new Date(move.date))}</td><td><b>{move.itemName}</b></td><td>{move.type}</td><td className={move.quantity > 0 ? 'positive' : 'negative'}>{move.quantity > 0 ? '+' : ''}{move.quantity}</td><td>{move.reference}</td><td>{move.balance}</td></tr>)}</tbody></table></section></> }
function Finance() { return <><Heading eyebrow="Business performance" title="Finance" text="Operational sales, expenses, payments, and profit in MYR." /><section className="metrics"><Metric label="Revenue" value={money.format(18420)} note="This month" /><Metric label="Cost of goods" value={money.format(6910)} note="Materials and production" /><Metric label="Outstanding" value={money.format(2840)} note="Across 4 invoices" /><Metric label="Gross profit" value={money.format(11510)} note="62.5% margin" /></section><section className="panel finance-chart"><PanelTitle eyebrow="Cash position" title="Income and expenses" action="Export" /><div className="mock-lines"><i /><i /><i /><i /><i /><i /><i /></div><div className="legend"><span>● Income</span><span>● Expenses</span></div></section></> }
function Insights() { return <><Heading eyebrow="Production intelligence" title="Insights" text="Understand lead time, bottlenecks, defects, and material waste." /><section className="insight-grid"><article className="panel"><p className="eyebrow">Average lead time</p><strong className="big-number">3.4 days</strong><p className="positive">↓ 8% from last month</p></article><article className="panel"><p className="eyebrow">First-pass quality</p><strong className="big-number">96.2%</strong><p>12 defects across 316 units</p></article><article className="panel chart-card"><PanelTitle eyebrow="Six-week trend" title="Jobs completed" action="View report" /><div className="mock-chart">{[42,64,48,82,68,92].map((h,i)=><i key={i} style={{height:`${h}%`}} />)}</div></article></section></> }
function Settings({ notify }: { notify: (text: string) => void }) { return <><Heading eyebrow="Workspace" title="Business settings" text="Configure your company identity and production defaults." /><section className="panel settings-grid"><div><h3>Business profile</h3><label>Company name<input defaultValue="Three Line Apparel" /></label><label>Registration number<input defaultValue="202601012345" /></label><label>Currency<select defaultValue="MYR"><option>MYR — Malaysian Ringgit</option></select></label></div><div><h3>Document defaults</h3><label>Invoice prefix<input defaultValue="INV" /></label><label>Default tax rate<input defaultValue="0" type="number" /></label><label>Payment terms<select><option>Due on receipt</option><option>7 days</option><option>30 days</option></select></label></div><button className="primary" onClick={() => notify('Business settings saved in demo')}>Save settings</button></section></> }

function Modal({ kind, job, close, onJob, onContact, onItem, notify }: { kind: Exclude<ModalKind,null>; job: PrintJob|null; close:()=>void; onJob:(x:PrintJob)=>void; onContact:(x:Contact)=>void; onItem:(x:InventoryItem)=>void; notify:(x:string)=>void }) {
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget)
    if (kind === 'job') onJob({ id:`J-${1049+Math.floor(Math.random()*30)}`, title:String(data.get('title')), customerId:'C-01', customerName:String(data.get('customer')), method:String(data.get('method')) as PrintJob['method'], quantity:Number(data.get('quantity')), dueDate:String(data.get('dueDate')), status:'Pending' })
    if (kind === 'contact') onContact({ id:`C-${Date.now()}`, name:String(data.get('name')), type:String(data.get('type')) as Contact['type'], phone:String(data.get('phone')), email:String(data.get('email')) })
    if (kind === 'item') onItem({ id:`I-${Date.now()}`, sku:String(data.get('sku')), name:String(data.get('name')), category:String(data.get('category')), quantity:Number(data.get('quantity')), reorderLevel:Number(data.get('reorder')), unit:String(data.get('unit')) })
    if (kind === 'quote') notify('Quotation Q-3028 saved as draft'); if (kind === 'movement') notify('Stock receipt recorded in demo'); close()
  }
  if (kind === 'jobDetail' && job) return <div className="modal-backdrop" onMouseDown={close}><section className="drawer" onMouseDown={(e)=>e.stopPropagation()}><ModalHeader title={`${job.id} · ${job.title}`} close={close} /><div className="detail-hero"><Status value={job.status} /><h2>{job.customerName}</h2><p>{job.method} · {job.quantity} units · Due {date.format(new Date(job.dueDate))}</p></div><h3>Production progress</h3><div className="timeline">{['Artwork approved','Materials prepared','Printing','Finishing','Quality check'].map((step,i)=><div className={i<2?'done':i===2?'current':''} key={step}><span>{i<2?'✓':i+1}</span><div><b>{step}</b><small>{i<2?'Completed':i===2?'In progress':'Waiting'}</small></div></div>)}</div><div className="detail-actions"><button className="secondary">Print jobsheet</button><button className="primary" onClick={()=>{notify('Job stage updated in demo');close()}}>Advance stage</button></div></section></div>
  if (kind === 'jobDetail') return null
  const config = modalConfig[kind]
  return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={(e)=>e.stopPropagation()}><ModalHeader title={config.title} close={close} /><form onSubmit={submit} className="modal-form">{config.fields.map((field)=><Field key={field.name} {...field} />)}{kind==='job'&&<div className="workflow-preview"><b>Default production flow</b><div>{['Artwork','Print','Finish','QC'].map((x,i)=><span key={x}>{i+1}. {x}</span>)}</div></div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">{config.submit}</button></div></form></section></div>
}

type FieldSpec={name:string;label:string;type?:string;options?:string[];defaultValue?:string;placeholder?:string}
const modalConfig: Record<Exclude<ModalKind,null|'jobDetail'>,{title:string;submit:string;fields:FieldSpec[]}> = {
  job:{title:'New print job',submit:'Create job',fields:[{name:'customer',label:'Customer',options:['Meridian Studio','Northstar FC','Cedar & Co.']},{name:'title',label:'Job title',placeholder:'e.g. 100 navy polo shirts'},{name:'method',label:'Print method',options:['Sublimation','Silkscreen','DTF','Embroidery','Heat Press','Custom']},{name:'quantity',label:'Total quantity',type:'number',defaultValue:'1'},{name:'dueDate',label:'Due date',type:'date',defaultValue:'2026-09-05'}]},
  quote:{title:'New quotation',submit:'Save draft quotation',fields:[{name:'customer',label:'Customer',options:['Meridian Studio','Northstar FC','New customer']},{name:'title',label:'Description',placeholder:'Corporate apparel order'},{name:'quantity',label:'Quantity',type:'number',defaultValue:'100'},{name:'unitPrice',label:'Unit price (RM)',type:'number',defaultValue:'28'},{name:'deposit',label:'Deposit (%)',type:'number',defaultValue:'50'}]},
  contact:{title:'Add contact',submit:'Add contact',fields:[{name:'type',label:'Contact type',options:['Customer','Supplier']},{name:'name',label:'Business or customer name',placeholder:'e.g. Harmoni Events'},{name:'phone',label:'Phone',type:'tel',placeholder:'+60 12-345 6789'},{name:'email',label:'Email',type:'email',placeholder:'orders@example.com'}]},
  item:{title:'Add inventory item',submit:'Add item',fields:[{name:'name',label:'Item name',placeholder:'e.g. White dry-fit shirt · L'},{name:'sku',label:'SKU',placeholder:'TS-DRY-WHT-L'},{name:'category',label:'Category',options:['Garment','Ink','Film','Thread','Packaging']},{name:'quantity',label:'Opening quantity',type:'number',defaultValue:'0'},{name:'unit',label:'Unit',options:['pcs','L','kg','sheets','rolls']},{name:'reorder',label:'Reorder level',type:'number',defaultValue:'10'}]},
  movement:{title:'Log stock movement',submit:'Record movement',fields:[{name:'item',label:'Inventory item',options:['Black dry-fit shirt · M','DTF ink · Black','DTF transfer film · A3']},{name:'type',label:'Movement',options:['Receipt','Consumption','Adjustment']},{name:'quantity',label:'Quantity',type:'number',defaultValue:'10'},{name:'reference',label:'Reference',placeholder:'PO-0833'}]},
}
function Field({name,label,type='text',options,defaultValue,placeholder}:FieldSpec){return <label>{label}{options?<select name={name} defaultValue={defaultValue}>{options.map(x=><option key={x}>{x}</option>)}</select>:<input name={name} type={type} defaultValue={defaultValue} placeholder={placeholder} required />}</label>}
function ModalHeader({title,close}:{title:string;close:()=>void}){return <header className="modal-header"><div><span className="prototype-label">Interactive demo</span><h2>{title}</h2></div><button onClick={close} aria-label="Close">×</button></header>}
function Brand({compact=false}:{compact?:boolean}){return <div className="brand"><span>MZ</span>{compact?<b>MZPrintFlow</b>:<div><b>MZPrintFlow</b><small>Print operations</small></div>}</div>}
function Heading({eyebrow,title,text,action,onAction}:{eyebrow:string;title:string;text:string;action?:string;onAction?:()=>void}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action&&<button className="primary" onClick={onAction}>{action}</button>}</div>}
function Metric({label,value,note,danger=false}:{label:string;value:string|number;note:string;danger?:boolean}){return <article><span>{label}</span><strong className={danger?'danger':''}>{value}</strong><small>{note}</small></article>}
function Status({value}:{value:PrintJobStatus}){return <span className={`status status-${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>}
function PanelTitle({eyebrow,title,action,onAction}:{eyebrow:string;title:string;action:string;onAction?:()=>void}){return <div className="panel-title"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><button className="ghost" onClick={onAction}>{action}</button></div>}
function Notice({tone,title,text}:{tone:string;title:string;text:string}){return <div className={`notice ${tone}`}><b>{title}</b><span>{text}</span></div>}
